### PR TITLE
Re-export the `ics23.cosmos.v1` Protobuf definitions from the `ics23` crate

### LINKED ISSUE #10: Duplicate proto files for ICS23
## Crate

`ibc` and `ibc-proto`

## Problem Definition

Currently, the canonical place for the .proto file of ICS23 is [confio/ics23](https://github.com/confio/ics23/blob/master/proofs.proto). The Cosmos-SDK and IBC-go repos both copy the `proofs.proto` file from confio/ics23 as a "third party proto". The `ibc-proto` crate similarly copies the same `proofs.proto` file from Cosmos-SDK. In general, the state of .proto files is quite fractured, but ICS23 is even more so.

This fracturing creates the problem that there are two version of the ICS23 specs:

- in `ibc_proto` we have [this](https://github.com/informalsystems/ibc-rs/blob/master/proto/src/prost/ics23.rs)
- in the "canonical" confio/ics23 there is [this](https://github.com/confio/ics23/blob/master/rust/src/ics23.rs)

The two files are not identical, since the confio/ics23 version has been recently changed, and the updates did not propagate downstream into CosmosSDK nor into ibc-proto (yet). Even if the files were on par, there would still be two legit definitions of the same data structures, for every structure in `ics23.rs`.

A specific instance where this is problematic is that we need [awkward code](https://github.com/informalsystems/ibc-rs/pull/842/commits/718ec1f845031821cbdf644cb90275c1543fe65b) to convert from `ics23::ProofSpec` to the identical data structure `ibc_proto::ics23::ProfSpec`.

## Proposal

Ideally, crate `ibc` should depend on a single .proto definition of the ICS23 files.

## Acceptance Criteria

- The fix is to avoid generating `ics23.rs` in `ibc-proto` crate and rely entirely on confio/ics23. This means that [ibc_proto::ics23](https://github.com/informalsystems/ibc-rs/blob/master/proto/src/prost/ics23.rs) should not exist anymore.

The long-term fix is to have all .proto files related to IBC stored in a single unified place, e.g., repo cosmos/ibc. This is a larger eco-system problem, however, which we don't need to track with this issue.

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by romac**
Closes: #10

The proto definitions are exported both under the `ibc_proto::cosmos::ics23::v1` module and under the `ibc_proto::ics23` module for backward source compatiblity.

This is nonetheless a breaking change as it may break compilation or trigger warnings in code which relied on these definitions being different than the ones in `ics23`.

> **Warning**
> Note that because the code generated by `pbjson-build` is not `no_std` compatible, the serde annotations on the generated protos are only emitted when the `std` feature of `ibc-proto` is enabled, which is unfortunate but I didn't find a way around that.

### CODE REVIEW

**Comment by erwanor** [comment]
Thanks for your work on this @romac. 

Re: pbjson, that seems like a necessary tradeoff, and we can help with getting upstream to get `no_std` compliance. It would be great to merge this soon because our ICS23 support hinges on this + a release, and we're already a little behind schedule 🙏

**Review by adizere — APPROVED** [review]
Not familiar with the changes in `.github/workflows/rust.yml`, otherwise the changes look good as far as I understand.

Thanks Romain!

**Comment by romac** [comment]
Before merging this and doing a release, I would just like to get some feedback from @plafer or @Farhad-Shabani on whether or not they use the JSON impls on no_std or are aware of anyone using those. Either way this shouldn't prevent us from doing a release on Monday, but maybe then as an alpha to give some time to find an alternative solution (eg. no_std support in pbjson) before the final release.

**Comment by plafer** [comment]
I don't have time to do a thorough analysis of this right now, but we do not use the JSON impls internally. Off the top of my head, I do not know of anyone that does.

**Comment by romac** [comment]
I am told we have a potential user of JSON serialization in `no_std` context, so let's do an alpha release and then try to find a way to restore `no_std` compat for the generated code.

**Comment by romac** [comment]
@erwanor `ibc-proto` v0.31.0-alpha.1 is out: https://github.com/cosmos/ibc-proto-rs/releases/tag/v0.31.0-alpha.1

**Pull request merged**
