### PR TITLE
cargo: prepare release `0.33`

### PR DESCRIPTION
**Pull request by erwanor**
This PR:
- #123 
-  #124

### CODE REVIEW

**Comment by erwanor** [comment]
Odd, I just ran `unclog build > CHANGELOG.md` and staged the changes but it looks like it has removed some dates and reformatted a bunch of other entries. What command do you typically use?

**Comment by romac** [comment]
I usually run `unclog build -u` and then copy-paste the section for the new release at the top of the `CHANGELOG` and add the date manually (+ some reformatting when needed).

**Comment by romac** [comment]
I've updated the contributing guidelines with more detailed information.

**Comment by erwanor** [comment]
Thanks, I'll restage the changelog

**Review by Farhad-Shabani — APPROVED** [review]
:pray:

**Pull request merged**
