### PR TITLE
Feature-gate generated tonic transport code behind `transport` feature

### LINKED ISSUE #237: Make `transport` optional (potential WASM support)
I believe this should be two steps:

1. Feature-gating a bit more granularly

default could remain as-is. Would be something like a change from this:

```
[features]
default = ["std", "client"]
client = ["std", "dep:tonic", "tonic/codegen", "tonic/transport", "tonic/prost"]
server = ["std", "dep:tonic", "tonic/codegen", "tonic/transport", "tonic/prost"]
```

to this:

```
[features]
default = ["std", "client", "transport"]
client = ["std", "dep:tonic", "tonic/codegen", "tonic/prost"]
server = ["std", "dep:tonic", "tonic/codegen", "tonic/prost"]
transport = ["tonic/transport"]
```

2. providing a way to `tonic_build` without the `transport` feature. I'm not sure if that's part of the `proto-compiler` tool

This comment looks relevant: https://github.com/hyperium/tonic/issues/1538#issuecomment-2049778792

I'd be happy to make a PR, since I was able to build a client partially with the feature-gating locally, but couldn't proceed with the `proto-compiler` tool (instructions don't work, or I did something wrong, it requires having a `--ics` and `--nft` param)

### PR DESCRIPTION
**Pull request by dakom**
fixes #237

### CODE REVIEW

**Comment by romac** [comment]
Thanks for the PR! Can you please rebase this on top of `main`?

It's a bit of a bummer that we have duplicate the generated code but I indeed do not see a way around that. Ideally we would be able to configure an attribute to be applied to the generated transport code (much like for the client and server modules with `client_attribute` and `server_attribute`) but that functionality is not present yet in tonic.

I think we go with this solution for now, but it would be great if you could also open an issue on the tonic repository to see if we can ever get this implemented in tonic itself.

**Comment by dakom** [comment]
yeah, I also didn't see another way around that for now 😅 

> Can you please rebase this on top of main?

done!

> it would be great if you could also open an issue on the tonic repository to see if we can ever get this implemented in tonic itself.

done: https://github.com/hyperium/tonic/issues/1941

**Comment by tony-iqlusion** [comment]
@dakom thanks for opening an issue! We have a similar problem in `cosmos-sdk-proto`

**Comment by dakom** [comment]
ahh, @tony-iqlusion I see: https://github.com/cosmos/cosmos-rust/blob/c19d64b92e14133cadcdc00410adf5355a3e3891/proto-build/src/main.rs#L291 ... I don't know the generated protobufs well enough to attempt that, but, it seems to work. @romac if you want me to attempt that same change here and try it out in a browser-based test, I'm cool with that, just let me know (it sure is nice to not have separately generated files) :)

**Comment by romac** [comment]
Yes please, sounds good!

**Comment by dakom** [comment]
Done in https://github.com/cosmos/ibc-proto-rs/pull/240 ... totally just ripped off the solution from @tony-iqlusion ;) tested in-browser with a minimal gRPC request over gRPC-web and it works :D

**Pull request merged**
